services:
  postgres:
    image: 'postgres:17.3'
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=battleship_db
    env_file:
      - .env